name: Environment Name
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create Environment
      uses: actions/create-environment@v1
      with:
        environment: github-pages
